# Generated by Django 5.1.6 on 2025-02-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approval',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
