# Generated by Django 5.1.6 on 2025-02-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiry',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacture',
            field=models.CharField(max_length=50),
        ),
    ]
